on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Render-dashboard
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dashboarddown:
    name: Render-dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.1'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: System dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('DESCRIPTION') }}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
