on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Render-dashboard
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dashboarddown:
    name: Render-dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: System dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev r-cran-remotes r-cran-rcmdcheck
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown")
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('DESCRIPTION') }}
      - name: Install package
        run: R CMD INSTALL .
      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Commit results
        run: |
          git clone https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git --branch history --single-branch
          cp vignettes/available*.csv cranis
          cd cranis
          git init
          git add .
          git commit -m 'new data'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:history --force
